### ISSUE TITLE
Support for Auto Prefixing CSS

### ISSUE THREAD

**Issue by johannwagner** [websecurify/babel-plugin-import-css-to-jss#2]
Hey Guys,

is there a way to enable auto prefixing for all css tags? After transforming into JS, there is no appropiate plugins, which can do that. Maybe you can tell me, how to archive this.. Maybe this is an option in jss..

Best Regards, 
   Johann

**Comment by pdparchitect** [comment]
Once the file is imported you can post process the object. It is just a normal JS object so you can use Object.entries map filter and so on to restructure the CSS in whatever is required. This babel plugin simply import the CSS and there is no easy way to extend this mechanism with configurable options.
